//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class MaxDBMessages {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal MaxDBMessages() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaxDBMessages", typeof(MaxDBMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Data adapter is null..
    /// </summary>
    internal static string adapter_null {
        get {
            return ResourceManager.GetString("adapter_null", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Reconnect for admin session not supported..
    /// </summary>
    internal static string admin_reconnect {
        get {
            return ResourceManager.GetString("admin_reconnect", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot put ASCII data into this LONG column..
    /// </summary>
    internal static string asciiputtolong {
        get {
            return ResourceManager.GetString("asciiputtolong", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot read ASCII data from this LONG column..
    /// </summary>
    internal static string asciireadfromlong {
        get {
            return ResourceManager.GetString("asciireadfromlong", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Base table name is not found. Probably FOR UPDATE suffix is not specified..
    /// </summary>
    internal static string basetable_notfound {
        get {
            return ResourceManager.GetString("basetable_notfound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Missing IN/INOUT parameter at row {0} and position {1}..
    /// </summary>
    internal static string batchmissingin {
        get {
            return ResourceManager.GetString("batchmissingin", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Called DB procedure in batch contained OUT or INOUT parameters..
    /// </summary>
    internal static string batchprocout {
        get {
            return ResourceManager.GetString("batchprocout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL statement in batch would create a result set..
    /// </summary>
    internal static string batchresultset {
        get {
            return ResourceManager.GetString("batchresultset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Batch command number {0} generates a result set.
    /// </summary>
    internal static string batchresultset_withnumber {
        get {
            return ResourceManager.GetString("batchresultset_withnumber", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Overflow in {0}..
    /// </summary>
    internal static string bigint_overflow {
        get {
            return ResourceManager.GetString("bigint_overflow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Radix must be between 2 and 36.
    /// </summary>
    internal static string bigint_radix_overflow {
        get {
            return ResourceManager.GetString("bigint_radix_overflow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Underflow in {0}..
    /// </summary>
    internal static string bigint_underflow {
        get {
            return ResourceManager.GetString("bigint_underflow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot put binary data into this LONG column..
    /// </summary>
    internal static string binaryputtolong {
        get {
            return ResourceManager.GetString("binaryputtolong", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot read binary data from this LONG column..
    /// </summary>
    internal static string binaryreadfromlong {
        get {
            return ResourceManager.GetString("binaryreadfromlong", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Read {0} bytes at position {1} in buffer of length {2}..
    /// </summary>
    internal static string chunkoverflow {
        get {
            return ResourceManager.GetString("chunkoverflow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Column index {0} was not found..
    /// </summary>
    internal static string colindex_notfound {
        get {
            return ResourceManager.GetString("colindex_notfound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Column name {0} was not found..
    /// </summary>
    internal static string colname_notfound {
        get {
            return ResourceManager.GetString("colname_notfound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Can not allocate buffer for the column name.
    /// </summary>
    internal static string columnname_buffer {
        get {
            return ResourceManager.GetString("columnname_buffer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Failed to get the value since column&apos;s value is NULL.
    /// </summary>
    internal static string columnvalue_null {
        get {
            return ResourceManager.GetString("columnvalue_null", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Connection down, session released.
    /// </summary>
    internal static string commconnectiondown {
        get {
            return ResourceManager.GetString("commconnectiondown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Crash.
    /// </summary>
    internal static string commcrash {
        get {
            return ResourceManager.GetString("commcrash", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to OK.
    /// </summary>
    internal static string commok {
        get {
            return ResourceManager.GetString("commok", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Packet limit.
    /// </summary>
    internal static string commpacketlimit {
        get {
            return ResourceManager.GetString("commpacketlimit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Receive line down.
    /// </summary>
    internal static string commrecvlinedown {
        get {
            return ResourceManager.GetString("commrecvlinedown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Released.
    /// </summary>
    internal static string commreleased {
        get {
            return ResourceManager.GetString("commreleased", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Restart required.
    /// </summary>
    internal static string commrestartrequired {
        get {
            return ResourceManager.GetString("commrestartrequired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Send line down.
    /// </summary>
    internal static string commsendlinedown {
        get {
            return ResourceManager.GetString("commsendlinedown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Server or DB unknown.
    /// </summary>
    internal static string commserverdbunknown {
        get {
            return ResourceManager.GetString("commserverdbunknown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Shutdown.
    /// </summary>
    internal static string commshutdown {
        get {
            return ResourceManager.GetString("commshutdown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Task limit.
    /// </summary>
    internal static string commtasklimit {
        get {
            return ResourceManager.GetString("commtasklimit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Time out.
    /// </summary>
    internal static string commtimeout {
        get {
            return ResourceManager.GetString("commtimeout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unknown request.
    /// </summary>
    internal static string communknownrequest {
        get {
            return ResourceManager.GetString("communknownrequest", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Would block.
    /// </summary>
    internal static string commwouldblock {
        get {
            return ResourceManager.GetString("commwouldblock", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Secure connect using challenge response authentication is not supported.
    /// </summary>
    internal static string connection_challengeresponsenotsupported {
        get {
            return ResourceManager.GetString("connection_challengeresponsenotsupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Can not set isolation level.
    /// </summary>
    internal static string connection_isolationlevel {
        get {
            return ResourceManager.GetString("connection_isolationlevel", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Connection is not opened..
    /// </summary>
    internal static string connection_notopened {
        get {
            return ResourceManager.GetString("connection_notopened", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Connect failed, wrong format of server challenge [{0}] .
    /// </summary>
    internal static string connection_wrongserverchallengereceived {
        get {
            return ResourceManager.GetString("connection_wrongserverchallengereceived", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Reply is garbled..
    /// </summary>
    internal static string connectreply_garbled {
        get {
            return ResourceManager.GetString("connectreply_garbled", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot convert data {0} to type {1}..
    /// </summary>
    internal static string conversion_data {
        get {
            return ResourceManager.GetString("conversion_data", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot convert .NET type {0} to SQL type {1}..
    /// </summary>
    internal static string conversion_netsql {
        get {
            return ResourceManager.GetString("conversion_netsql", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Result of arithmetic operation leads to an overflow or a division by 0..
    /// </summary>
    internal static string conversion_SpecialNullValue {
        get {
            return ResourceManager.GetString("conversion_SpecialNullValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot convert SQL type {0} to .NET type {1}..
    /// </summary>
    internal static string conversion_sqlnet {
        get {
            return ResourceManager.GetString("conversion_sqlnet", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Structure member {0} has unsupported data type {1}..
    /// </summary>
    internal static string conversion_structuretype {
        get {
            return ResourceManager.GetString("conversion_structuretype", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot convert VDN number [{0}]..
    /// </summary>
    internal static string conversion_VDNnumber {
        get {
            return ResourceManager.GetString("conversion_VDNnumber", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to [{0}] (at {1}): {2}.
    /// </summary>
    internal static string databaseexception {
        get {
            return ResourceManager.GetString("databaseexception", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to [{0}]: {1}.
    /// </summary>
    internal static string databaseexception_woerrpos {
        get {
            return ResourceManager.GetString("databaseexception_woerrpos", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Column nullable unknown.
    /// </summary>
    internal static string dbnull_unknown {
        get {
            return ResourceManager.GetString("dbnull_unknown", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Error.
    /// </summary>
    internal static string error {
        get {
            return ResourceManager.GetString("error", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Execution failed.
    /// </summary>
    internal static string exec_failed {
        get {
            return ResourceManager.GetString("exec_failed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Fetch data error.
    /// </summary>
    internal static string fetch_data_failed {
        get {
            return ResourceManager.GetString("fetch_data_failed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Fetch operation delivered no data part..
    /// </summary>
    internal static string fetch_nodatapart {
        get {
            return ResourceManager.GetString("fetch_nodatapart", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to getObject function failed.
    /// </summary>
    internal static string getobject_failed {
        get {
            return ResourceManager.GetString("getobject_failed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot change key during hash operation.
    /// </summary>
    internal static string hash_change_key {
        get {
            return ResourceManager.GetString("hash_change_key", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot connect to host {0}:{1}..
    /// </summary>
    internal static string host_connect_failed {
        get {
            return ResourceManager.GetString("host_connect_failed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Index {0} is out of range.
    /// </summary>
    internal static string index_outofrange {
        get {
            return ResourceManager.GetString("index_outofrange", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Internal error: connection field is null, but should not..
    /// </summary>
    internal static string internal_connectionnull {
        get {
            return ResourceManager.GetString("internal_connectionnull", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Internal error: parse id is null..
    /// </summary>
    internal static string internal_invalidParseid {
        get {
            return ResourceManager.GetString("internal_invalidParseid", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Internal error: input parameter at index {0} was not expected..
    /// </summary>
    internal static string internal_unexpectedinput {
        get {
            return ResourceManager.GetString("internal_unexpectedinput", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Internal error: output parameter at index {0} was not expected..
    /// </summary>
    internal static string internal_unexpectedoutput {
        get {
            return ResourceManager.GetString("internal_unexpectedoutput", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid column index {0}..
    /// </summary>
    internal static string invalid_columnindex {
        get {
            return ResourceManager.GetString("invalid_columnindex", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid column {0}..
    /// </summary>
    internal static string invalid_columnname {
        get {
            return ResourceManager.GetString("invalid_columnname", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid data type..
    /// </summary>
    internal static string invalid_datatype {
        get {
            return ResourceManager.GetString("invalid_datatype", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Internal error: Invalid start position for LONG data..
    /// </summary>
    internal static string invalid_startposition {
        get {
            return ResourceManager.GetString("invalid_startposition", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The password is invalid..
    /// </summary>
    internal static string invalidpassword {
        get {
            return ResourceManager.GetString("invalidpassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected a long data part as reply to get value..
    /// </summary>
    internal static string longdata_expected {
        get {
            return ResourceManager.GetString("longdata_expected", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to IN or OUT parameter missing at position {0}..
    /// </summary>
    internal static string missinginout {
        get {
            return ResourceManager.GetString("missinginout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Moving backwards in Blob is not supported..
    /// </summary>
    internal static string movebackwardinblob {
        get {
            return ResourceManager.GetString("movebackwardinblob", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Could not get column names from database kernel..
    /// </summary>
    internal static string no_columnnames {
        get {
            return ResourceManager.GetString("no_columnnames", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No data found..
    /// </summary>
    internal static string nodata_found {
        get {
            return ResourceManager.GetString("nodata_found", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No password given..
    /// </summary>
    internal static string nopassword {
        get {
            return ResourceManager.GetString("nopassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No user name given..
    /// </summary>
    internal static string nouser {
        get {
            return ResourceManager.GetString("nouser", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Object is closed..
    /// </summary>
    internal static string objectisclosed {
        get {
            return ResourceManager.GetString("objectisclosed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to OMS stream object is not supported.
    /// </summary>
    internal static string oms_unsupported {
        get {
            return ResourceManager.GetString("oms_unsupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter {0} is null..
    /// </summary>
    internal static string parameter_null {
        get {
            return ResourceManager.GetString("parameter_null", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter truncated.
    /// </summary>
    internal static string parameter_truncated {
        get {
            return ResourceManager.GetString("parameter_truncated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unable to find original pool for the connection &apos;{0}&apos;.
    /// </summary>
    internal static string pool_not_found {
        get {
            return ResourceManager.GetString("pool_not_found", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Receive of connect failed..
    /// </summary>
    internal static string recv_connect {
        get {
            return ResourceManager.GetString("recv_connect", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Result set is positioned after last row..
    /// </summary>
    internal static string resultset_afterlast {
        get {
            return ResourceManager.GetString("resultset_afterlast", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Result set is positioned before first row..
    /// </summary>
    internal static string resultset_beforefirst {
        get {
            return ResourceManager.GetString("resultset_beforefirst", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select command is null..
    /// </summary>
    internal static string select_null {
        get {
            return ResourceManager.GetString("select_null", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The number value {0} is not supported..
    /// </summary>
    internal static string special_number_unsupported {
        get {
            return ResourceManager.GetString("special_number_unsupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL command doesn&apos;t return a result set..
    /// </summary>
    internal static string sqlcommand_noresultset {
        get {
            return ResourceManager.GetString("sqlcommand_noresultset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL statement does not call a DB procedure..
    /// </summary>
    internal static string sqlstatement_noprocedure {
        get {
            return ResourceManager.GetString("sqlstatement_noprocedure", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL statement is null..
    /// </summary>
    internal static string sqlstatement_null {
        get {
            return ResourceManager.GetString("sqlstatement_null", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL statement would generate a result set..
    /// </summary>
    internal static string sqlstatement_resultset {
        get {
            return ResourceManager.GetString("sqlstatement_resultset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL statement is too long. Increase the DB parameter PACKET_SIZE..
    /// </summary>
    internal static string sqlstatement_toolong {
        get {
            return ResourceManager.GetString("sqlstatement_toolong", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Certificate error:.
    /// </summary>
    internal static string ssl_certificate {
        get {
            return ResourceManager.GetString("ssl_certificate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to SQL statement cancelled..
    /// </summary>
    internal static string statement_cancelled {
        get {
            return ResourceManager.GetString("statement_cancelled", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to IO Exception in stream read: {0}.
    /// </summary>
    internal static string stream_ioexception {
        get {
            return ResourceManager.GetString("stream_ioexception", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Binary data argument cannot be converted to character/structured stream..
    /// </summary>
    internal static string streamconversion_bytes {
        get {
            return ResourceManager.GetString("streamconversion_bytes", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Character data argument cannot be converted to binary/structured stream..
    /// </summary>
    internal static string streamconversion_string {
        get {
            return ResourceManager.GetString("streamconversion_string", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Stream is empty or already closed..
    /// </summary>
    internal static string streamisatend {
        get {
            return ResourceManager.GetString("streamisatend", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Number of items in input and structure do not match (required {0}, input was {1})..
    /// </summary>
    internal static string structure_arraywronglength {
        get {
            return ResourceManager.GetString("structure_arraywronglength", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Conversion of structure element of type {0} from {1} is not possible..
    /// </summary>
    internal static string structure_element_conversion {
        get {
            return ResourceManager.GetString("structure_element_conversion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Input structure element #{0} is null..
    /// </summary>
    internal static string structure_element_null {
        get {
            return ResourceManager.GetString("structure_element_null", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Conversion of structure element of type {0} failed (overflow), value was {1}..
    /// </summary>
    internal static string structure_element_overflow {
        get {
            return ResourceManager.GetString("structure_element_overflow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to TableDirect parameter is not supported.
    /// </summary>
    internal static string tabledirect_unsupported {
        get {
            return ResourceManager.GetString("tabledirect_unsupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Timeout.
    /// </summary>
    internal static string timeout {
        get {
            return ResourceManager.GetString("timeout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unknown data type..
    /// </summary>
    internal static string unknown_datatype {
        get {
            return ResourceManager.GetString("unknown_datatype", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;unknown&gt;.
    /// </summary>
    internal static string unknowntype {
        get {
            return ResourceManager.GetString("unknowntype", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter must be named..
    /// </summary>
    internal static string unnamed_parameter {
        get {
            return ResourceManager.GetString("unnamed_parameter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter {0}: value too large..
    /// </summary>
    internal static string valueoverflow {
        get {
            return ResourceManager.GetString("valueoverflow", resourceCulture);
        }
    }
}
