// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBConnection.Ping(MaxDB.Data.MaxDBProtocol.MaxDBComm)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.BasicProcedurePutValue.CloseStream")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.BytesTranslator.TransBinaryStreamForInput(System.IO.Stream,System.Int32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.CharDataTranslator.GetDateTime(MaxDB.Data.Utilities.ByteArray)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.DataPart.FillWithReader(System.IO.TextReader,MaxDB.Data.Utilities.ByteArray,MaxDB.Data.MaxDBProtocol.PutValue)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.DataPart.FillWithStream(System.IO.Stream,MaxDB.Data.Utilities.ByteArray,MaxDB.Data.MaxDBProtocol.PutValue)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.DateTranslator.TransStringForInput(System.String)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.MaxDBComm.Cancel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.MaxDBComm.Connect(System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.MaxDBComm.Open(MaxDB.Data.ConnectArgs,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.NumericTranslator.GetBigDecimal(MaxDB.Data.Utilities.ByteArray)~MaxDB.Data.Utilities.BigDecimal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.NumericTranslator.TransStringForInput(System.String)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.StringTranslator.GetBigDecimal(MaxDB.Data.Utilities.ByteArray)~MaxDB.Data.Utilities.BigDecimal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.StringTranslator.GetBoolean(MaxDB.Data.Utilities.ByteArray)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.StringTranslator.TransBinaryStreamForInput(System.IO.Stream,System.Int32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.StringTranslator.TransCharacterStreamForInput(System.IO.Stream,System.Int32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.StructureTranslator.TransBinaryStreamForInput(System.IO.Stream,System.Int32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.StructureTranslator.TransCharacterStreamForInput(System.IO.Stream,System.Int32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.TimestampTranslator.TransStringForInput(System.String)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.TimeTranslator.TransStringForInput(System.String)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.MaxDBProtocol.UnicodeProcedurePutValue.CloseStream")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.Utilities.Auth.ParseServerChallenge(MaxDB.Data.MaxDBProtocol.DataPartVariable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.Utilities.RawByteReader.Read(System.Char[],System.Int32,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.Utilities.SocketClass.#ctor(System.String,System.Int32,System.Int32,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.Utilities.VDNNumber.Number2BigDecimal(System.Byte[])~MaxDB.Data.Utilities.BigDecimal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.Utilities.VDNNumber.Number2String(System.Byte[],System.Boolean,System.Int32,System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA5351:Do Not Use Broken Cryptographic Algorithms", Justification = "<Pending>", Scope = "member", Target = "~M:MaxDB.Data.Utilities.Crypt.ScrammMD5(System.Byte[],System.Byte[],System.Byte[],System.Byte[])~System.Byte[]")]

