using System;

namespace MaxDBDataProvider
{
	/// <summary>
	/// Summary description for MaxDBType.
	/// </summary>
	public enum MaxDBType
	{
		Fixed = SQLDBC_SQLType.SQLDBC_SQLTYPE_FIXED,
		Float = SQLDBC_SQLType.SQLDBC_SQLTYPE_FLOAT,
		CharA = SQLDBC_SQLType.SQLDBC_SQLTYPE_CHA,
		CharB = SQLDBC_SQLType.SQLDBC_SQLTYPE_CHB,
		StrA = SQLDBC_SQLType.SQLDBC_SQLTYPE_STRA,
		StrB = SQLDBC_SQLType.SQLDBC_SQLTYPE_STRB,
		Date = SQLDBC_SQLType.SQLDBC_SQLTYPE_DATE,
		Time = SQLDBC_SQLType.SQLDBC_SQLTYPE_TIME,
		VFloat = SQLDBC_SQLType.SQLDBC_SQLTYPE_VFLOAT,
		TimeStamp = SQLDBC_SQLType.SQLDBC_SQLTYPE_TIMESTAMP,
		Boolean = SQLDBC_SQLType.SQLDBC_SQLTYPE_BOOLEAN,
		Unicode = SQLDBC_SQLType.SQLDBC_SQLTYPE_UNICODE,
		SmallInt = SQLDBC_SQLType.SQLDBC_SQLTYPE_SMALLINT,
		Integer = SQLDBC_SQLType.SQLDBC_SQLTYPE_INTEGER,
		VarCharA = SQLDBC_SQLType.SQLDBC_SQLTYPE_VARCHARA,
		VarCharB = SQLDBC_SQLType.SQLDBC_SQLTYPE_VARCHARB,
		StrUni = SQLDBC_SQLType.SQLDBC_SQLTYPE_STRUNI,
		VarCharUni = SQLDBC_SQLType.SQLDBC_SQLTYPE_VARCHARUNI
	}
}
